### ISSUE TITLE
Deleting selected shape keys

### ISSUE THREAD

**Issue by gonzou3d** [p2or/blender-shapekey-extras#3]
Hi poor,

I wonder if you could add a new feature which'll allow me to **_delete_** visible shape keys?
E.g. I've got 30 shape keys (10 for controlling _'nose'_, 10 for _'ears'_ and 10 for _'mouth'_). Now I want to **_delete_** let's say all the _'mouth'_ shape keys. 

Could you add analogous **_delete_** feature like you did with previous ones? (e.g. I type _'mouth'_ in _Include Only_ window to make only them visible. Then I press the **_DELETE SHAPEKEYS_** button [which you'll add] and get rid of them).

Thanks for help once again, it'll surely make my work easier :).

**Comment by p2or** [comment]
Hey Paul,

To ensure that only the desired keys will be deleted, there is a new _Print Selection to Console_ Button since this operation could be risky (IMO). For this reason I've also implemented Undo/Redo. That means that you can press `Ctrl`+`Z` or `Ctrl`+`Shift`+`Z` for every operation as usual.

 Please checkout the latest release: https://github.com/p2or/blender-shapekeyextras/releases

**Comment by gonzou3d** [comment]
Thanks,

Sounds great! I'll check this out ASAP.
