### ISSUE TITLE
Is it possible to input multiple vertex groups' names in the shapekey's Blend window?

### ISSUE THREAD

**Issue by gonzou3d** [p2or/blender-shapekey-extras#5]
I'd like to input multiple vertex groups names in a shapekey's _Blend_ window. It'll allow me to modify multiple parameters (multiple vertex groups) of the mesh using one single shapekey. Right now I am allowed to affect only one vertex group by a shapekey. It's very time consuming and uncomfortable. Is there a way to change it using scripting?
![poor_blend_issue](https://user-images.githubusercontent.com/16025201/29428327-15d4292a-838d-11e7-8234-d6b50dc4dd77.png)

**Comment by p2or** [comment]
Hey Paul,

please check out the [new release](https://github.com/p2or/blender-shapekey-extras/releases). Note that the UI to merge the vertex groups is only available in *Object Mode* since it's not possible merging the groups in *Edit Mode*. However, let me know if that's _real problem_, then we can switch to *Object Mode* and back programmatically.

Cheers,
Christian

BTW: You can [watch this repository](https://help.github.com/articles/watching-repositories/), if you like to get notifications for releases, issues etc per mail automatically.

**Comment by gonzou3d** [comment]
Hello,

Thanks a lot! Works great! Very clear and smart solution. I don't think that the fact you can merge the groups only in Object Mode is a real problem.

P.s. If I find something else worth improving I'll let you know ASAP.

See you,
Paul
